services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  BeechIt\SolrfalTextextract\:
    resource: '../Classes/*'

  BeechIt\SolrfalTextextract\EventListener\AfterFileInfoHasBeenAddedToDocumentEventListener:
    tags:
      - name: event.listener
        identifier: 'solrfal/extract-content-from-pdf'
